name: C/C++ CI

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        include:
        - os: macOS-latest
          COMPILER_FLAGS: ''
          TESTS_EXECUTABLE: 'tests/Tests'

        - os: ubuntu-latest
          COMPILER_FLAGS: '-Wall -Wextra'
          TESTS_EXECUTABLE: 'tests/Tests'

        - os: windows-latest
          COMPILER_FLAGS: ''
          TESTS_EXECUTABLE: 'tests/$BUILD_TYPE/Tests.exe'

    steps:
    - uses: actions/checkout@v1

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${{ matrix.COMPILER_FLAGS }}" -D2DENGINE_BUILD_TESTS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Run Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./${{ matrix.TESTS_EXECUTABLE }}
